title: Bharath Kumar Reddy Kristipati.  # Add a space after the period

logo: 1.png # Use a relative path to logo image 

description: Automation Engineer - SDET # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

 # Verify ownership through Search Console  

email: bharath.kristipati@gmail.com # Allow visitors to contact you
